name: app369
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^11.0.0
  image_picker: ^1.0.7
  url_launcher: ^6.3.1
  intl: ^0.19.0
  geolocator: ^13.0.1
  google_maps_flutter: ^2.10.0
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.8
  flutter_snake_navigationbar: ^0.6.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/logo_ph.png

