name: app369
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  mobile_scanner: ^5.1.0
  font_awesome_flutter: ^11.0.0
  image_picker: ^1.0.7
  url_launcher: ^6.3.1
  intl: ^0.19.0
  geolocator: ^13.0.1
  google_maps_flutter: ^2.10.0
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.8
  flutter_snake_navigationbar: ^0.6.1
  http: ^1.1.0
  supabase_flutter: ^2.6.0
  app_links: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true
  assets:
    - assets/logo_ph.png
    - assets/logo_app.png
    - assets/logo_montana.png
    - assets/logo_verde_montana.png
    - assets/xd.png
    - assets/logo-ios.png
    - assets/padrehurtado.png
    - assets/logo-ios-fixed.png


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo-ios-fixed.png"
  min_sdk_android: 21