-- SCHEMA DE BASE DE DATOS: MI PADRE HURTADO
-- FECHA: 14/08/2026

-- 1. TABLA DE COMERCIOS
CREATE TABLE IF NOT EXISTS comercios (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  rut text UNIQUE NOT NULL,
  razon_social text,
  nombre_fantasia text NOT NULL,
  giro text,
  telefono text,
  email text,
  direccion_matriz text,
  comuna text DEFAULT 'Padre Hurtado',
  representante_legal text,
  rut_representante_legal text,
  categoria text,
  decreto_numero text,
  fecha_inicio date,
  fecha_termino date,
  archivo_url text,
  estado text DEFAULT 'Pendiente',
  fecha_registro timestamp with time zone DEFAULT now()
);

-- 2. TABLA DE SUCURSALES
CREATE TABLE IF NOT EXISTS sucursales (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  comercio_id uuid REFERENCES comercios(id) ON DELETE CASCADE,
  nombre text NOT NULL,
  direccion text,
  telefono text,
  horario text,
  estado text DEFAULT 'Activa'
);

-- 3. TABLA DE BENEFICIOS
CREATE TABLE IF NOT EXISTS beneficios (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comercio_id uuid REFERENCES comercios(id) ON DELETE CASCADE,
  titulo text NOT NULL,
  descripcion text,
  dias_uso text,
  horario_uso text,
  condiciones text,
  estado text DEFAULT 'Activo'
);

-- 4. TABLA DE ADMINISTRADORES DE COMERCIOS
CREATE TABLE IF NOT EXISTS administradores_comercios (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  rut text UNIQUE NOT NULL,
  nombre text,
  email text NOT NULL,
  comercio_id uuid REFERENCES comercios(id) ON DELETE SET NULL,
  estado text DEFAULT 'Pendiente',
  password_temporal text,
  enlace_activacion text,
  fecha_creacion timestamp with time zone DEFAULT now()
);

-- 5. TABLA DE SOLICITUDES DE CANJE (TRANSACCIONAL)
CREATE TABLE IF NOT EXISTS solicitudes_canje (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  comercio_id uuid REFERENCES comercios(id) ON DELETE CASCADE,
  sucursal_id uuid REFERENCES sucursales(id) ON DELETE CASCADE,
  beneficio_id bigint REFERENCES beneficios(id) ON DELETE CASCADE,
  vecino_nombre text NOT NULL,
  estado text DEFAULT 'Pendiente', -- Pendiente, Aprobado, Rechazado, Cancelado
  motivo_rechazo text,
  fecha_solicitud timestamp with time zone DEFAULT now(),
  fecha_respuesta timestamp with time zone
);

-- HABILITAR REALTIME PARA CANJES
ALTER PUBLICATION supabase_realtime ADD TABLE solicitudes_canje;
